---
title: "Understand Logistic Regression"
subtitle: "why we use it and what does it provide"
author: "[王　超辰 | Chaochen Wang](https://wangcc.me)"
date: "2019-07-08 17:00~18:00 @CSS"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      countdown: 60000
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r xaringan-themer, include = FALSE}
library(xaringanthemer)
mono_light(
  base_color = "#1c5253",
  header_font_google = google_font("Josefin Sans"),
  # text_font_google   = google_font("M PLUS Rounded 1c", "300", "300i"),
  text_font_google = google_font("Noto Sans JP", "300", "300i"), 
  code_font_google   = google_font("Droid Mono"),
  text_bold_color = "#B03A2E",
  link_color = "#f0f0f0",
  title_slide_background_image = "pic/"
)
# write_xaringan_theme(text_bold_color = "#FF4333")
```



class: middle
# objectives

- Use a logistic regression model to compare the log odds of disease in two groups $\Rightarrow$ estimate a crude odds ratio for **a binary exposure**.

- Use a logistic regression model to compare the odds of disease for a categorical exposure with **2 or more levels**.



---
class:middle
## Odds and Odds ratio (OR)

- The odds of a disease is defined as:  $$\mathbf{Odds} = \frac{n_{D+}}{n_{D-}}$$ <br> where $D+$ indicates individuals **with disease (such as lung cancer)** <br> $D-$ indicates individuals **without the disease**


- The ratio of the odds between groups is a **measure for comparing the frequency of disease:** $$\mathbf{OR} = \frac{\mathbf{Odds}_{E+}}{\mathbf{Odds}_{E-}}$$ <br> where $E+$ indicates individuals **with exposure (such as smoking)** <br> $E-$ indicates individuals **without the exposure**



---
class:middle
## Logistic regression model in a nutshell

$$
\begin{aligned}
\mathbf{Odds}_{E+} & = \mathbf{Odds}_{E-} \times \mathbf{OR} \\
\Rightarrow \log(\mathbf{Odds}_{E+}) & = \log(\mathbf{Odds}_{E-}) + \log(\mathbf{OR})
\end{aligned}
$$


Where, <br> $\log(\mathbf{Odds}_{E-})$ is called **"Baseline log odds in the unexposed group"** <br> $\log(\mathbf{OR})$
